trigger:
- master

parameters:
  - name: 'environment'
    type: string
    default: dev
    values:
      - dev
      - test

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Terraform_CI_Stage
    displayName: 'Terraform CI Stage'
    jobs:

      - job: Terraform_CI
        displayName: 'Terraform CI Job'
        steps:

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'MyAzureServiceConnection'
              backendAzureRmResourceGroupName: 'test_rg'
              backendAzureRmStorageAccountName: 'cicdstorageacc'
              backendAzureRmContainerName: 'azureblob-container'
              backendAzureRmKey: '${{ parameters.environment }}.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'MyAzureServiceConnection'
              commandOptions: '-var-file="${{ parameters.environment }}.tfvars" -out=tfplan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Plan Artifact'
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform/tfplan'
              ArtifactName: 'tfplan'
              publishLocation: 'Container'

